version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.23.0
  - dependency-name: update-notifier
    versions:
    - 5.1.0
  - dependency-name: tcp-port-used
    versions:
    - 1.0.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: eslint
  - dependency-name: update-notifier
  - dependency-name: tcp-port-used
  - dependency-name: "@ledgerhq/hw-transport-node-hid"
  - dependency-name: open
  - dependency-name: danger
  - dependency-name: danger
  - dependency-name: danger-plugin-yarn
  - dependency-name: jest
  - dependency-name: jest-environment-node
  - dependency-name: strip-ansi
  - dependency-name: strip-ansi-cli
  - dependency-name: ascii-table
  - dependency-name: bn.js
  - dependency-name: bs58
  - dependency-name: chalk
  - dependency-name: flagged-respawn
  - dependency-name: is-ci
  - dependency-name: mixpanel
  - dependency-name: ncp
  - dependency-name: rimraf
  - dependency-name: stoppable
  - dependency-name: update-notifier
  - dependency-name: uuid
  - dependency-name: v8flags
  - dependency-name: yargs